# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Pir_V4
                                 A QGIS plugin
 This plugins allows edition and sharing of medata.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-11
        copyright            : (C) 2023 by ENSG
        email                : aubin.bettiol@ensg.eu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Pir_V4 class from file Pir_V4.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pir_v4 import Pir_V4
    return Pir_V4(iface)
